-- =====================================================================
-- 0004_pipeline.sql — Shreeja Finance Platform
-- Loan pipeline: loan_applications, loan_stage_entries, documents,
-- valuation_slabs. Also adds deferred FK on eligibility_evaluations.
-- =====================================================================

-- ─── loan_applications ───────────────────────────────────────────────
-- One row per loan file.
-- Stage order: cibil → bank → valuation → fi → approval → disbursement
-- application_no: human-readable e.g. SF-2026-00001
CREATE TABLE loan_applications (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  application_no          TEXT NOT NULL UNIQUE, -- generated by service layer (SF-YYYY-NNNNN)
  -- Parties
  customer_id             UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  created_by_profile_id   UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  dealer_id               UUID REFERENCES dealers(id) ON DELETE RESTRICT,   -- one dealer max (L10); null if staff-created
  staff_id                UUID REFERENCES staff(id) ON DELETE RESTRICT,      -- null if dealer-created
  -- File details
  product_type            product_type NOT NULL,
  vehicle_details         JSONB NOT NULL DEFAULT '{}',  -- make, model, year, variant, chassis_no, engine_no, etc.
  requested_amount        NUMERIC(14,2) NOT NULL,
  -- Outcomes (populated as the file progresses)
  approved_amount         NUMERIC(14,2),
  disbursed_amount        NUMERIC(14,2),
  submitted_lender_id     UUID REFERENCES lenders(id) ON DELETE RESTRICT,   -- set on submit
  -- State machine
  current_stage           loan_stage NOT NULL DEFAULT 'cibil',
  status                  application_status NOT NULL DEFAULT 'draft',
  -- Timestamps for business rules
  approved_at             TIMESTAMPTZ,          -- set when status → approved
  disbursed_at            TIMESTAMPTZ,          -- set when status → disbursed
  rejected_at             TIMESTAMPTZ,
  cancelled_at            TIMESTAMPTZ,
  -- For 90-day block tracking (J1 job scans this)
  blocked_90d_at          TIMESTAMPTZ,
  -- Internal
  internal_notes          TEXT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_loan_applications
  BEFORE UPDATE ON loan_applications
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ─── Now wire the deferred FK from eligibility_evaluations ───────────
ALTER TABLE eligibility_evaluations
  ADD CONSTRAINT fk_eligibility_loan_application
  FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE RESTRICT;

-- ─── loan_stage_entries ──────────────────────────────────────────────
-- APPEND-ONLY stage ledger per loan file.
-- Corrections = new row with remarks. Never update or delete (L4).
-- data jsonb shape is stage-specific:
--   cibil:      { bureau: string, score: int, report_date: date }
--   bank:       { bank_name: string, account_type: string, vintage_months: int }
--   valuation:  { valuation_date: date, valuer: string, assessed_value: numeric, depreciation_pct: numeric }
--   fi:         { fi_date: date, field_agent: string, residence_verified: bool, remarks: string }
--   approval:   { approved_amount: numeric, approved_by: string, conditions: string[] }
--   disbursement: { disbursed_amount: numeric, disbursed_to: string, utr: string, bank_name: string }
CREATE TABLE loan_stage_entries (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_application_id   UUID NOT NULL REFERENCES loan_applications(id) ON DELETE RESTRICT,
  stage                 loan_stage NOT NULL,
  entered_by_profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  outcome               TEXT NOT NULL CHECK (outcome IN ('pass', 'fail', 'pending', 'rework')),
  remarks               TEXT,
  data                  JSONB NOT NULL DEFAULT '{}',
  -- No updated_at — append-only
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── documents ───────────────────────────────────────────────────────
-- Uploaded files for a loan application. Files stored on VPS CDN (not Supabase Storage).
-- cdn_path: CDN-relative path served by Nginx.
--   Production: /var/www/skfinance/cdn/<path>  (absolute on VPS)
--   Local dev:  ./cdn/<path>                   (relative to project root)
--   Path convention: loans/<application_no>/<party>/<doc_type>/<uuid>.<ext>
--   The Express file-upload service writes the file to disk and stores only
--   the relative portion (e.g. "loans/SF-2026-00001/applicant/aadhaar/abc123.pdf").
--   Full URL = CDN_BASE_URL + "/" + cdn_path  (CDN_BASE_URL in .env)
-- party: applicant | co_applicant | guarantor
CREATE TABLE documents (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_application_id   UUID NOT NULL REFERENCES loan_applications(id) ON DELETE RESTRICT,
  party                 TEXT NOT NULL CHECK (party IN ('applicant', 'co_applicant', 'guarantor')),
  doc_type              TEXT NOT NULL,          -- matches policy_documents.doc_type values
  cdn_path              TEXT NOT NULL,          -- CDN-relative path (see comment above)
  original_filename     TEXT,
  mime_type             TEXT,
  file_size_bytes       INT,
  uploaded_by_profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  -- Verification (staff/admin)
  verified              BOOLEAN NOT NULL DEFAULT FALSE,
  verified_by           UUID REFERENCES profiles(id) ON DELETE RESTRICT,
  verified_at           TIMESTAMPTZ,
  rejection_reason      TEXT,                  -- if returned for re-upload
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_documents
  BEFORE UPDATE ON documents
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- ─── valuation_slabs ─────────────────────────────────────────────────
-- In-house depreciation table, admin-tunable.
-- The valuation service uses: assessed_value = market_value * (1 - depreciation_pct/100)
-- vehicle_category: new_car | used_car | commercial_vehicle
-- age_band: e.g. '0-1', '1-3', '3-5', '5-7', '7-10', '10+'
CREATE TABLE valuation_slabs (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_category    product_type NOT NULL,
  age_band            TEXT NOT NULL,            -- e.g. '0-1' means 0–1 year old
  depreciation_pct    NUMERIC(5,2) NOT NULL,    -- e.g. 5.00 = 5%
  CONSTRAINT uq_valuation_slab UNIQUE (vehicle_category, age_band),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_updated_at_valuation_slabs
  BEFORE UPDATE ON valuation_slabs
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
